import type { ParcelInput } from "@/lib/types";

/**
 * Sample listing inventory.
 *
 * IMPORTANT: these are not real parcels and none of them is for sale. There is
 * no public feed of land listings that carries structured water-right data, and
 * inventing plausible-looking listings and presenting them as genuine would be
 * exactly the kind of fabrication this codebase is built to avoid. So the
 * inventory is synthetic, labelled as such everywhere it surfaces, and carries
 * no broker, contact or parcel identifiers that could be mistaken for real.
 *
 * What it is good for is real: it exercises the scoring engine, the match
 * engine and the map end to end, and it defines the shape a live feed would
 * have to produce. Replacing it means implementing `ListingSource` against an
 * MLS, a land brokerage feed or a county records scrape — everything
 * downstream of `getListings()` already works.
 *
 * Coordinates are approximate county centroids, so the pins land in the right
 * county rather than on a specific property.
 */

export interface Listing {
  id: string;
  /** Marketing headline, written the way these listings are actually written. */
  headline: string;
  /** What the parcel actually is, in plain terms. */
  description: string;
  /** The line in the listing that a careful buyer should react to. */
  tell: string;
  lat: number;
  lng: number;
  price: number;
  /** Everything the engine needs to score it. */
  input: ParcelInput;
}

/** Defaults so each listing only states what makes it distinctive. */
function listing(
  id: string,
  headline: string,
  description: string,
  tell: string,
  lat: number,
  lng: number,
  price: number,
  input: Partial<ParcelInput> & Pick<ParcelInput, "jurisdictionCode" | "county" | "acres">,
): Listing {
  return {
    id,
    headline,
    description,
    tell,
    lat,
    lng,
    price,
    input: {
      label: headline,
      intent: "irrigated-crop",
      surfaceRight: "unknown",
      adjudication: "unknown",
      appurtenant: "unknown",
      previouslySevered: "unknown",
      wellStatus: "none",
      aquiferTrend: "unknown",
      inManagedDistrict: "unknown",
      documents: [],
      legalAccess: "unknown",
      mineralEstateSevered: "unknown",
      conservationEasement: "unknown",
      existingLiens: "unknown",
      tribalOrFederalClaimsInBasin: "unknown",
      askingPrice: price,
      buyerCountry: "US",
      ...input,
    },
  };
}

export const LISTINGS: Listing[] = [
  // ---------------------------------------------------------------- Oklahoma
  listing(
    "ok-texas-county-quarter",
    "Irrigated quarter, Texas County",
    "A 160-acre quarter over the Ogallala in the Oklahoma panhandle with a permitted well and an OWRB allocation tied to the overlying acreage.",
    "Allocation scales with acreage here, so contiguity with the neighbouring quarter is worth more than the price difference suggests.",
    36.75,
    -101.48,
    640_000,
    {
      jurisdictionCode: "US-OK",
      county: "Texas",
      acres: 160,
      irrigatedAcresPlanned: 130,
      decreedAcreFeet: 320,
      surfaceRight: "none",
      adjudication: "not-applicable",
      appurtenant: "yes",
      previouslySevered: "no",
      wellStatus: "permitted-and-registered",
      wellDepthFt: 320,
      wellYieldGpm: 900,
      aquiferTrend: "declining",
      inManagedDistrict: "yes",
      documents: ["state-permit-or-decree", "deed-with-water-language", "well-log-and-completion-report", "title-commitment", "survey"],
      documentedUseYears: 18,
      longestNonUseGapYears: 0,
      legalAccess: "yes",
      mineralEstateSevered: "yes",
      conservationEasement: "no",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "no",
      closeTimelineDays: 90,
    },
  ),
  listing(
    "ok-beaver-dryland",
    "Beaver County grass, 320 acres",
    "Unirrigated native grass with stock ponds and one exempt domestic well. No production allocation in place.",
    "Cheap per acre because there is no irrigation allocation attached — the overlying acreage entitlement still exists but has never been applied for.",
    36.75,
    -100.52,
    288_000,
    {
      jurisdictionCode: "US-OK",
      county: "Beaver",
      acres: 320,
      intent: "pasture-grazing",
      surfaceRight: "none",
      adjudication: "not-applicable",
      appurtenant: "unknown",
      previouslySevered: "unknown",
      wellStatus: "registered-only",
      wellYieldGpm: 30,
      aquiferTrend: "declining",
      inManagedDistrict: "yes",
      documents: ["deed-with-water-language", "title-commitment"],
      legalAccess: "yes",
      mineralEstateSevered: "yes",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "no",
      closeTimelineDays: 60,
    },
  ),

  // ---------------------------------------------------------------- Colorado
  listing(
    "co-prowers-ditch",
    "Arkansas Valley farm with ditch shares",
    "240 acres of irrigated ground in Prowers County served by mutual ditch company shares, with a 1968 priority and a long-established rotation.",
    "The shares are personal property and do not move with the deed. The listing says 'water rights included' and that is not the same thing.",
    38.05,
    -102.4,
    1_080_000,
    {
      jurisdictionCode: "US-CO",
      county: "Prowers",
      acres: 240,
      irrigatedAcresPlanned: 200,
      surfaceRight: "ditch-company-shares",
      priorityDate: "1968",
      decreedAcreFeet: 480,
      adjudication: "fully-adjudicated",
      appurtenant: "unknown",
      previouslySevered: "unknown",
      wellStatus: "none",
      aquiferTrend: "stable",
      inManagedDistrict: "no",
      documents: ["deed-with-water-language", "title-commitment"],
      documentedUseYears: 12,
      longestNonUseGapYears: 2,
      legalAccess: "yes",
      mineralEstateSevered: "no",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "no",
      closeTimelineDays: 45,
    },
  ),
  listing(
    "co-rio-grande-senior",
    "San Luis Valley hay ground, senior decree",
    "180 acres with an 1889 decreed surface right, fully adjudicated in Water Division 3, and continuous documented use.",
    "A pre-1890 adjudicated priority is the rare thing on this list. Expect the price to reflect it and the diligence to confirm it.",
    37.62,
    -105.88,
    1_350_000,
    {
      jurisdictionCode: "US-CO",
      county: "Alamosa",
      acres: 180,
      irrigatedAcresPlanned: 150,
      surfaceRight: "decreed-appropriative",
      priorityDate: "1889",
      decreedAcreFeet: 540,
      adjudication: "fully-adjudicated",
      appurtenant: "yes",
      previouslySevered: "no",
      wellStatus: "permitted-and-registered",
      wellYieldGpm: 700,
      aquiferTrend: "declining",
      inManagedDistrict: "yes",
      documents: [
        "state-permit-or-decree",
        "deed-with-water-language",
        "title-commitment",
        "historical-use-records",
        "well-log-and-completion-report",
        "pump-test",
        "survey",
      ],
      documentedUseYears: 30,
      longestNonUseGapYears: 0,
      legalAccess: "yes",
      mineralEstateSevered: "no",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "no",
      closeTimelineDays: 120,
    },
  ),

  // ------------------------------------------------------------------- Texas
  listing(
    "tx-hale-pivot",
    "Hale County pivot ground",
    "640 acres under two pivots on the southern Ogallala, inside a groundwater conservation district with a metered annual allocation.",
    "Saturated thickness here is falling. The allocation is the ceiling, not the pump, and the district has reduced it before.",
    34.07,
    -101.82,
    1_920_000,
    {
      jurisdictionCode: "US-TX",
      county: "Hale",
      acres: 640,
      irrigatedAcresPlanned: 400,
      decreedAcreFeet: 1_200,
      surfaceRight: "none",
      adjudication: "not-applicable",
      appurtenant: "yes",
      previouslySevered: "unknown",
      wellStatus: "permitted-and-registered",
      wellDepthFt: 280,
      wellYieldGpm: 850,
      aquiferTrend: "steeply-declining",
      inManagedDistrict: "yes",
      documents: ["deed-with-water-language", "title-commitment", "well-log-and-completion-report", "survey"],
      documentedUseYears: 20,
      longestNonUseGapYears: 0,
      legalAccess: "yes",
      mineralEstateSevered: "yes",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "no",
      closeTimelineDays: 60,
    },
  ),
  listing(
    "tx-edwards-recharge",
    "Hill Country tract over the Edwards",
    "95 acres of oak and cedar above the Edwards recharge zone with an unregistered well and no EAA permit.",
    "Groundwater here is capped and permitted by the Edwards Aquifer Authority. A well without a permit is not a water supply.",
    29.88,
    -98.72,
    712_500,
    {
      jurisdictionCode: "US-TX",
      county: "Comal",
      acres: 95,
      intent: "domestic-homestead",
      surfaceRight: "none",
      adjudication: "not-applicable",
      appurtenant: "unknown",
      previouslySevered: "unknown",
      wellStatus: "unregistered",
      wellYieldGpm: 60,
      aquiferTrend: "declining",
      inManagedDistrict: "yes",
      documents: ["deed-with-water-language"],
      legalAccess: "yes",
      mineralEstateSevered: "yes",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "no",
      closeTimelineDays: 30,
    },
  ),

  // ------------------------------------------------------------------ Kansas
  listing(
    "ks-finney-lema",
    "Finney County circle inside a LEMA",
    "480 acres with a 1972 appropriation and ten years of filed annual water use reports, inside a Local Enhanced Management Area.",
    "The LEMA has cut permitted pumping across the area. Buy the reduced allocation, not the paper right.",
    38.05,
    -100.72,
    1_248_000,
    {
      jurisdictionCode: "US-KS",
      county: "Finney",
      acres: 480,
      irrigatedAcresPlanned: 380,
      surfaceRight: "permitted-appropriative",
      priorityDate: "1972",
      decreedAcreFeet: 950,
      adjudication: "fully-adjudicated",
      appurtenant: "yes",
      previouslySevered: "no",
      wellStatus: "permitted-and-registered",
      wellYieldGpm: 1_100,
      aquiferTrend: "declining",
      inManagedDistrict: "yes",
      documents: ["state-permit-or-decree", "deed-with-water-language", "title-commitment", "historical-use-records", "well-log-and-completion-report"],
      documentedUseYears: 10,
      longestNonUseGapYears: 1,
      legalAccess: "yes",
      mineralEstateSevered: "no",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "no",
      closeTimelineDays: 75,
    },
  ),

  // ----------------------------------------------------------------- Montana
  listing(
    "mt-gallatin-creek",
    "Gallatin Valley creek bottom",
    "120 acres with a pre-1973 claim in the statewide adjudication, currently at temporary preliminary decree, and a working headgate.",
    "A claim is not a decree. Objections in the adjudication can still reduce the flow rate and acreage you thought you bought.",
    45.68,
    -111.2,
    1_440_000,
    {
      jurisdictionCode: "US-MT",
      county: "Gallatin",
      acres: 120,
      intent: "pasture-grazing",
      irrigatedAcresPlanned: 90,
      surfaceRight: "decreed-appropriative",
      priorityDate: "1901",
      decreedAcreFeet: 260,
      adjudication: "adjudication-pending",
      appurtenant: "yes",
      previouslySevered: "no",
      wellStatus: "permitted-and-registered",
      wellYieldGpm: 35,
      aquiferTrend: "stable",
      inManagedDistrict: "no",
      documents: ["state-permit-or-decree", "deed-with-water-language", "title-commitment", "historical-use-records", "survey"],
      documentedUseYears: 25,
      longestNonUseGapYears: 0,
      legalAccess: "yes",
      mineralEstateSevered: "no",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "yes",
      closeTimelineDays: 90,
    },
  ),

  // -------------------------------------------------------------- New Mexico
  listing(
    "nm-sierra-idle",
    "Sierra County river tract",
    "200 acres along the Rio Grande with a permitted right that has not been exercised for eleven years.",
    "New Mexico forfeits a right after four years of non-use. Eleven years is not a bargain, it is a defect.",
    33.13,
    -107.25,
    420_000,
    {
      jurisdictionCode: "US-NM",
      county: "Sierra",
      acres: 200,
      irrigatedAcresPlanned: 120,
      surfaceRight: "permitted-appropriative",
      priorityDate: "1955",
      decreedAcreFeet: 400,
      adjudication: "adjudication-pending",
      appurtenant: "unknown",
      previouslySevered: "unknown",
      wellStatus: "abandoned-or-unknown",
      aquiferTrend: "declining",
      inManagedDistrict: "no",
      documents: ["deed-with-water-language"],
      documentedUseYears: 0,
      longestNonUseGapYears: 11,
      legalAccess: "unknown",
      mineralEstateSevered: "unknown",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "yes",
      closeTimelineDays: 30,
    },
  ),

  // ------------------------------------------------------------------- Idaho
  listing(
    "id-jerome-espa",
    "Jerome County row-crop ground",
    "300 acres on the Eastern Snake Plain Aquifer with a 1948 groundwater right and membership in a ground water district.",
    "ESPA juniors face curtailment unless covered by an approved mitigation plan. Ask what the district assessment has run per acre.",
    42.72,
    -114.52,
    1_500_000,
    {
      jurisdictionCode: "US-ID",
      county: "Jerome",
      acres: 300,
      irrigatedAcresPlanned: 260,
      surfaceRight: "permitted-appropriative",
      priorityDate: "1948",
      decreedAcreFeet: 780,
      adjudication: "fully-adjudicated",
      appurtenant: "yes",
      previouslySevered: "no",
      wellStatus: "permitted-and-registered",
      wellYieldGpm: 1_400,
      aquiferTrend: "stable",
      inManagedDistrict: "yes",
      documents: ["state-permit-or-decree", "deed-with-water-language", "title-commitment", "historical-use-records", "well-log-and-completion-report", "pump-test"],
      documentedUseYears: 22,
      longestNonUseGapYears: 0,
      legalAccess: "yes",
      mineralEstateSevered: "no",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "no",
      closeTimelineDays: 90,
    },
  ),

  // ---------------------------------------------------------------- Nebraska
  listing(
    "ne-dundy-certified",
    "Dundy County certified irrigated acres",
    "160 acres with NRD-certified irrigated acres in a fully appropriated basin, plus a registered well.",
    "Certified acres are the asset in Nebraska. Get the certification in writing from the NRD, tied to the legal description.",
    40.18,
    -101.62,
    720_000,
    {
      jurisdictionCode: "US-NE",
      county: "Dundy",
      acres: 160,
      irrigatedAcresPlanned: 140,
      decreedAcreFeet: 380,
      surfaceRight: "none",
      adjudication: "not-applicable",
      appurtenant: "yes",
      previouslySevered: "no",
      wellStatus: "permitted-and-registered",
      wellYieldGpm: 800,
      aquiferTrend: "declining",
      inManagedDistrict: "yes",
      documents: ["state-permit-or-decree", "deed-with-water-language", "title-commitment", "well-log-and-completion-report", "assessment-history"],
      documentedUseYears: 16,
      longestNonUseGapYears: 0,
      legalAccess: "yes",
      mineralEstateSevered: "no",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "no",
      closeTimelineDays: 60,
    },
  ),

  // ----------------------------------------------------------------- Arizona
  listing(
    "az-cochise-unregulated",
    "Willcox basin farm, 320 acres",
    "Irrigated ground in a rural basin outside any Active Management Area, with two high-capacity wells and no pumping limit.",
    "No limit cuts both ways. There is nothing stopping a larger neighbour drilling deeper, and water levels here have fallen sharply.",
    32.25,
    -109.83,
    960_000,
    {
      jurisdictionCode: "US-AZ",
      county: "Cochise",
      acres: 320,
      irrigatedAcresPlanned: 280,
      decreedAcreFeet: 900,
      surfaceRight: "none",
      adjudication: "not-applicable",
      appurtenant: "yes",
      previouslySevered: "unknown",
      wellStatus: "registered-only",
      wellDepthFt: 640,
      wellYieldGpm: 1_000,
      aquiferTrend: "steeply-declining",
      inManagedDistrict: "no",
      documents: ["deed-with-water-language", "title-commitment", "well-log-and-completion-report"],
      documentedUseYears: 14,
      longestNonUseGapYears: 0,
      legalAccess: "yes",
      mineralEstateSevered: "no",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "yes",
      closeTimelineDays: 45,
    },
  ),

  // ------------------------------------------------------------------ Oregon
  listing(
    "or-umatilla-restricted",
    "Umatilla County block",
    "220 acres with a 1979 groundwater permit inside a designated Critical Ground Water Area.",
    "A 1979 priority in a restricted area is close to the end of the queue. Model it as unavailable in a dry year.",
    45.67,
    -119.28,
    770_000,
    {
      jurisdictionCode: "US-OR",
      county: "Umatilla",
      acres: 220,
      irrigatedAcresPlanned: 180,
      surfaceRight: "permitted-appropriative",
      priorityDate: "1979",
      decreedAcreFeet: 500,
      adjudication: "unadjudicated",
      appurtenant: "yes",
      previouslySevered: "no",
      wellStatus: "permitted-and-registered",
      wellYieldGpm: 600,
      aquiferTrend: "declining",
      inManagedDistrict: "yes",
      documents: ["state-permit-or-decree", "deed-with-water-language", "title-commitment"],
      documentedUseYears: 8,
      longestNonUseGapYears: 3,
      legalAccess: "yes",
      mineralEstateSevered: "no",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "yes",
      closeTimelineDays: 60,
    },
  ),

  // ---------------------------------------------------------- International
  listing(
    "uy-salto-campo",
    "Salto campo with irrigation reservoir",
    "405 hectares of mixed cropping ground in northern Uruguay with an authorised abstraction and an existing represa.",
    "Uruguay gives foreign buyers national treatment, but rural land must be held by natural persons or nominative-share companies.",
    -31.39,
    -57.96,
    1_620_000,
    {
      jurisdictionCode: "UY",
      county: "Salto",
      acres: 1_000,
      irrigatedAcresPlanned: 400,
      decreedAcreFeet: 1_100,
      surfaceRight: "permitted-appropriative",
      adjudication: "not-applicable",
      appurtenant: "yes",
      previouslySevered: "no",
      wellStatus: "permitted-and-registered",
      wellYieldGpm: 500,
      aquiferTrend: "stable",
      inManagedDistrict: "no",
      documents: ["state-permit-or-decree", "deed-with-water-language", "title-commitment", "survey"],
      documentedUseYears: 12,
      longestNonUseGapYears: 0,
      legalAccess: "yes",
      mineralEstateSevered: "no",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "no",
      ownershipStructure: "local-company",
      closeTimelineDays: 120,
    },
  ),
  listing(
    "cl-maule-derechos",
    "Maule orchard with registered water rights",
    "120 hectares in central Chile with perpetual consumptive rights registered in the Catastro Público de Aguas.",
    "Chilean water rights are separable from land and tradable. Confirm the right in both the DGA catastro and the Conservador.",
    -35.42,
    -71.67,
    1_780_000,
    {
      jurisdictionCode: "CL",
      county: "Maule",
      acres: 297,
      irrigatedAcresPlanned: 250,
      decreedAcreFeet: 850,
      surfaceRight: "decreed-appropriative",
      priorityDate: "1974",
      adjudication: "not-applicable",
      appurtenant: "yes",
      previouslySevered: "unknown",
      wellStatus: "permitted-and-registered",
      wellYieldGpm: 600,
      aquiferTrend: "declining",
      inManagedDistrict: "yes",
      documents: ["state-permit-or-decree", "deed-with-water-language", "title-commitment"],
      documentedUseYears: 20,
      longestNonUseGapYears: 0,
      legalAccess: "yes",
      mineralEstateSevered: "no",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "no",
      ownershipStructure: "local-company",
      closeTimelineDays: 120,
    },
  ),
  listing(
    "pt-alentejo-alqueva",
    "Alentejo olive grove inside the Alqueva perimeter",
    "150 hectares of established olive with a contracted allocation from the Alqueva network rather than a private borehole.",
    "Inside the perimeter the water is contractual. Land immediately outside it depends on a licence that has been curtailed in drought years.",
    38.22,
    -7.53,
    1_110_000,
    {
      jurisdictionCode: "PT",
      county: "Beja",
      acres: 371,
      irrigatedAcresPlanned: 340,
      decreedAcreFeet: 900,
      surfaceRight: "permitted-appropriative",
      adjudication: "not-applicable",
      appurtenant: "yes",
      previouslySevered: "no",
      wellStatus: "none",
      aquiferTrend: "declining",
      inManagedDistrict: "yes",
      documents: ["state-permit-or-decree", "deed-with-water-language", "title-commitment", "survey", "assessment-history"],
      documentedUseYears: 14,
      longestNonUseGapYears: 0,
      legalAccess: "yes",
      mineralEstateSevered: "no",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "no",
      ownershipStructure: "personal-freehold",
      closeTimelineDays: 90,
    },
  ),
  listing(
    "au-riverina-entitlement",
    "Riverina property with high-security entitlement",
    "260 hectares in the Murray-Darling with an unbundled high-security water access entitlement registered separately from the land.",
    "Entitlement is not allocation. Ask for the ten-year allocation history for this valley and class before pricing the water.",
    -34.75,
    -0.0 + 146.05,
    2_140_000,
    {
      jurisdictionCode: "AU",
      county: "Riverina, NSW",
      acres: 642,
      irrigatedAcresPlanned: 500,
      decreedAcreFeet: 1_600,
      surfaceRight: "permitted-appropriative",
      adjudication: "fully-adjudicated",
      appurtenant: "no",
      previouslySevered: "no",
      wellStatus: "none",
      aquiferTrend: "stable",
      inManagedDistrict: "yes",
      documents: ["state-permit-or-decree", "deed-with-water-language", "title-commitment", "historical-use-records", "survey"],
      documentedUseYears: 15,
      longestNonUseGapYears: 0,
      legalAccess: "yes",
      mineralEstateSevered: "yes",
      existingLiens: "no",
      tribalOrFederalClaimsInBasin: "no",
      ownershipStructure: "foreign-company",
      closeTimelineDays: 150,
    },
  ),
];

/**
 * The seam a real feed would implement. Everything downstream — map, matching,
 * detail pages, the wizard hand-off — consumes this and nothing else.
 */
export interface ListingSource {
  readonly name: string;
  /** True when the inventory is synthetic and must be labelled as such. */
  readonly sample: boolean;
  list(): Listing[];
  get(id: string): Listing | null;
}

export const sampleSource: ListingSource = {
  name: "Sample inventory",
  sample: true,
  list: () => LISTINGS,
  get: (id) => LISTINGS.find((l) => l.id === id) ?? null,
};

export function getListings(): Listing[] {
  return sampleSource.list();
}

export function getListing(id: string): Listing | null {
  return sampleSource.get(id);
}

export function listingsAreSample(): boolean {
  return sampleSource.sample;
}
